#!/bin/sh
# Regenerates RV_reference.v from RV/*.v.
#
# The point of the reference core is to give a student something to run in HDL
# mode before their own processor works, without handing them an answer key. So
# the hierarchy is flattened and every internal name is thrown away - except the
# register file, which is kept as a module with its array intact so that the
# simulator can still discover `RegBank` and show the 32 registers. Everything
# else arrives as `_017_` and `u42_`.
#
# PC_INIT is resolved at synthesis, so the netlist has 0x00400000 built into it.
# The wrapper module below keeps the parameter for interface compatibility and
# refuses to elaborate if it is given anything else.
#
# Usage:  sh examples/hdl/build_reference_core.sh        (from the repo root)
set -e

OUT=examples/hdl/RV_reference.v
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

yosys -q -p "
read_verilog RV/ALU.v RV/Shifter.v RV/Decoder.v RV/Extend.v RV/PC_Logic.v \
             RV/ProgramCounter.v RV/RegFile.v RV/MCycle.v RV/RV.v;
hierarchy -top RV -chparam PC_INIT 32'h00400000;
setattr -mod -set keep_hierarchy 1 RegFile;
proc; opt -full;
memory -nomap; opt -full;
flatten; opt -full;
pmuxtree;
opt -full; opt_clean -purge;
rename -hide RV/w:*;
rename -hide RV/c:* RV/t:RegFile %d;
opt_clean -purge;
rename -enumerate -pattern _%_ RV/w:*;
rename -enumerate -pattern u%_ RV/c:* RV/t:RegFile %d;
write_verilog -noattr $TMP/net.v;
stat
"

{
cat <<'HDR'
`timescale 1ns / 1ps
/*
----------------------------------------------------------------------------------
-- CG3207 reference processor core - PRE-SYNTHESISED, NOT SOURCE
--
-- Generated from the reference RTL by Yosys: one flattened module, all internal
-- names discarded. It is here so that HDL simulation mode has something to run
-- before your own processor does, and so that you have something to compare
-- against. It is not a model to copy, and reading it will teach you nothing
-- about how the processor is organised - that is the point.
--
-- What it is: RV32I plus the M extension (mul, mulh, mulhsu, mulhu, div, divu,
-- rem, remu), single cycle except for M, which stalls the PC for 32 or 64
-- cycles. Same ports as RV.v, so the fixed Wrapper.v instantiates it unchanged.
--
-- The register file is deliberately left as a module with its 32 x 32-bit array
-- intact, so the simulator can still show you the registers.
--
-- PC_INIT is fixed at 0x00400000. The parameter is still on the port list so
-- that Wrapper.v binds, but a different value will not elaborate - the generate
-- below then instantiates a module that does not exist, and the tool says so by
-- name rather than quietly running from the wrong address.
--
-- Regenerate with examples/hdl/build_reference_core.sh
----------------------------------------------------------------------------------
--	(c) Rajesh Panicker
--	License terms :
--	You are free to use this code as long as you
--		(i) DO NOT post it on any public repository;
--		(ii) use it only for educational purposes;
--		(iii) accept the responsibility to ensure that your implementation does not violate anyone's intellectual property.
--		(iv) accept that the program is provided "as is" without warranty of any kind or assurance regarding its suitability for any particular purpose;
--		(v) send an email to rajesh<dot>panicker<at>ieee.org briefly mentioning its use (except when used for the course CG3207 at the National University of Singapore);
--		(vi) retain this notice in this file as well as any files derived from this.
----------------------------------------------------------------------------------
*/

HDR

# Give the netlist's top back the parameter the fixed Wrapper binds by name, and
# guard it. The generate goes inside this same module rather than in a wrapper
# around it, so that `RegFile RegFile1(...)` stays a direct instantiation of the
# core - which is how the simulator finds RegBank and shows the registers.
sed -e '/^\/\* Generated by Yosys/d' \
    -e "s|^module RV(|module RV #(parameter PC_INIT = 32'h00400000) (|" "$TMP/net.v" |
awk '
  !done && /^endmodule$/ {
    print "  generate"
    print "    if (PC_INIT != 32'"'"'h00400000) begin : pc_init_check"
    print "      this_pre_synthesised_core_only_supports_PC_INIT_00400000 u_error();"
    print "    end"
    print "  endgenerate"
    done = 1
  }
  { print }
'
} > "$OUT"

# The Wrapper is fixed and not a solution to anything, so the reference bundle
# carries its own copy rather than the page reaching into RV/.
cp RV/Wrapper.v examples/hdl/Wrapper.v

echo "wrote $OUT ($(wc -l < "$OUT") lines) and examples/hdl/Wrapper.v"
