`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: NUS
// Engineer: Shahzor Ahmad, Rajesh C Panicker
// 
// Create Date: 27.09.2016 10:59:44
// Design Name: 
// Module Name: MCycle
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////
/* 
----------------------------------------------------------------------------------
--	(c) Shahzor Ahmad, Rajesh C Panicker
--	License terms :
--	You are free to use this code as long as you
--		(i) DO NOT post it on any public repository;
--		(ii) use it only for educational purposes;
--		(iii) accept that the program is provided "as is" without warranty of any kind or assurance regarding its suitability for any particular purpose;
--		(iv) send an email to rajesh.panicker@ieee.org briefly mentioning its use (except when used for the course CG3207 at the National University of Singapore);
--		(v) retain this notice in this file or any files derived from this.
----------------------------------------------------------------------------------
*/

module MCycle

    #(parameter width = 4) // Keep this at 4 to verify your algorithms with 4 bit numbers (easier). When using MCycle as a component in RV, generic map it to 32.
    (
        input CLK,
        input RESET, // Connect this to the reset of the RV processor.
        input Start, // Multi-cycle Enable. The control unit should assert this when an instruction with a multi-cycle operation is detected.
        input [1:0] MCycleOp, // Multi-cycle Operation. "00" for signed multiplication, "01" for unsigned multiplication, "10" for signed division, "11" for unsigned division. Generated by Control unit
        input [width-1:0] Operand1, // Multiplicand / Dividend
        input [width-1:0] Operand2, // Multiplier / Divisor
        output reg [width-1:0] Result1, // LSW of Product / Quotient
        output reg [width-1:0] Result2, // MSW of Product / Remainder
        output reg Busy // Set immediately when Start is set. Cleared when the Results become ready. This bit can be used to stall the processor while multi-cycle operations are on.
    );
    
// use the Busy signal to reset WE_PC to 0 in RV.v (aka "freeze" PC). The two signals are complements of each other
// since the IDLE_PROCESS is combinational, instantaneously asserts Busy once Start is asserted

    localparam IDLE = 1'b0 ;
    localparam COMPUTING = 1'b1 ;

    // Last value of count for each multiplication. Part-selected where they are
    // used, so the comparisons against count do not silently widen it.
    localparam COUNT_LAST_W  = width - 1 ;    // unsigned multiply
    localparam COUNT_LAST_2W = 2*width - 1 ;  // signed multiply, whose operands are sign extended to 2*width

    reg state = IDLE ;
    reg n_state = IDLE ;

    reg done = 1'b0 ;
    reg [7:0] count = 0 ; // assuming no computation takes more than 256 cycles.
    reg [2*width-1:0] temp_sum = 0 ;
    reg [2*width-1:0] shifted_op1 = 0 ;
    reg [2*width-1:0] shifted_op2 = 0 ;

    // What each of the above becomes at the next edge. The computation is
    // written as a sequence of steps over these, so that the registers
    // themselves are only ever assigned with <= , in one place.
    reg [7:0] n_count ;
    reg n_done ;
    reg [2*width-1:0] n_temp_sum ;
    reg [2*width-1:0] n_shifted_op1 ;
    reg [2*width-1:0] n_shifted_op2 ;
    reg [width-1:0] n_Result1 ;
    reg [width-1:0] n_Result2 ;

    always@(*) begin : IDLE_PROCESS
        // default outputs
        Busy = 1'b0 ;
        n_state = IDLE ;

        // reset
        if(~RESET)
            case(state)
                IDLE: begin
                    if(Start) begin // note: a mealy machine, since output depends on current state (IDLE) & input (Start)
                        n_state = COMPUTING ;
                        Busy = 1'b1 ;
                    end
                end
                COMPUTING: begin
                    if(~done) begin
                        n_state = COMPUTING ;
                        Busy = 1'b1 ;
                    end
                end
            endcase
    end


    always@(*) begin : COMPUTING_PROCESS // process which does the actual computation
        // Hold, unless something below says otherwise.
        n_count = count ;
        n_temp_sum = temp_sum ;
        n_shifted_op1 = shifted_op1 ;
        n_shifted_op2 = shifted_op2 ;
        n_Result1 = Result1 ;
        n_Result2 = Result2 ;
        n_done = 1'b0 ;

        // n_state == COMPUTING and state == IDLE implies we are just transitioning into COMPUTING
        if( RESET | (n_state == COMPUTING & state == IDLE) ) begin // 2nd condition is true during the very 1st clock cycle of the multiplication
            n_count = 0 ;
            n_temp_sum = 0 ;
            n_shifted_op1 = { {width{~MCycleOp[0] & Operand1[width-1]}}, Operand1 } ; // sign extend the operands
            n_shifted_op2 = { {width{~MCycleOp[0] & Operand2[width-1]}}, Operand2 } ;
        end

        // Guarded so that the cycle in which Busy falls - the one the processor uses to write the result back - does not run another iteration over it, and so that the results are held while idle.
        if( n_state == COMPUTING ) begin
            if( ~MCycleOp[1] ) begin // Multiply
                // if( ~MCycleOp[0] ), takes 2*'width' cycles to execute, returns signed(Operand1)*signed(Operand2)
                // if( MCycleOp[0] ), takes 'width' cycles to execute, returns unsigned(Operand1)*unsigned(Operand2)
                if( n_shifted_op2[0] ) // add only if b0 = 1
                    n_temp_sum = n_temp_sum + n_shifted_op1 ; // partial product for multiplication

                n_shifted_op2 = {1'b0, n_shifted_op2[2*width-1 : 1]} ;
                n_shifted_op1 = {n_shifted_op1[2*width-2 : 0], 1'b0} ;

                if( (MCycleOp[0] & n_count == COUNT_LAST_W[7:0]) | (~MCycleOp[0] & n_count == COUNT_LAST_2W[7:0]) ) // last cycle?
                    n_done = 1'b1 ;

                n_count = n_count + 1 ;
            end
            else begin // Supposed to be Divide. The dummy code below takes 1 cycle to execute, just returns the operands. Change this to signed [ if(~MCycleOp[0]) ] and unsigned [ if(MCycleOp[0]) ] division.
                // TODO (students): replace the one-cycle division placeholder.
                // It currently returns Operand1 in Result2 and Operand2 in Result1.
                n_temp_sum[2*width-1 : width] = Operand1 ;
                n_temp_sum[width-1 : 0] = Operand2 ;
                n_done = 1'b1 ;
            end

            n_Result2 = n_temp_sum[2*width-1 : width] ;
            n_Result1 = n_temp_sum[width-1 : 0] ;
        end
    end


    always@( posedge CLK ) begin : STATE_UPDATE_PROCESS // the only place any of this is registered
        state <= n_state ;
        count <= n_count ;
        done <= n_done ;
        temp_sum <= n_temp_sum ;
        shifted_op1 <= n_shifted_op1 ;
        shifted_op2 <= n_shifted_op2 ;
        Result1 <= n_Result1 ;
        Result2 <= n_Result2 ;
    end

endmodule
