/*
 * RV32M end-to-end: MCycle.v against the JS engine, and both against an
 * independent BigInt reference.
 *
 * A generated straight-line program runs every one of the eight M
 * instructions over a set of awkward operand pairs (most-negative, division
 * by zero, mixed signs, operands whose product needs the full 64 bits) and
 * stores each result to data memory. The same program is then executed three
 * ways and the three sets of stored words compared:
 *
 *   1. the page's JS functional model,
 *   2. the real Icarus/WASM simulation of RV/*.v, driven by the page's own
 *      generated testbench and memory images,
 *   3. a reference computed here with BigInt, following the RISC-V
 *      specification for division by zero and for -2**31 / -1.
 *
 * Agreement between 1 and 2 is what the processor change has to preserve;
 * 3 is there so that both agreeing on something wrong still fails.
 */
const fs = require('fs');
const path = require('path');
const { installExamplesFetch } = require('./examples_fetch');
let JSDOM;
try { JSDOM = require('jsdom').JSDOM; }
catch (e) { JSDOM = require(path.resolve(__dirname, 'node_modules/jsdom')).JSDOM; }

const ROOT = path.resolve(__dirname, '..');
const RV = path.join(ROOT, 'RV');
const ENGINE = process.env.HDL_ENGINE_DIR || path.join(ROOT, 'vendor', 'verisim');

const DESIGN = ['ALU.v', 'Decoder.v', 'Extend.v', 'MCycle.v', 'PC_Logic.v', 'ProgramCounter.v',
                'RegFile.v', 'Shifter.v', 'RV.v', 'Wrapper.v'];

const html = fs.readFileSync(path.join(ROOT, 'riscv_simulator.html'), 'utf8');
const CM6 = fs.readFileSync(path.join(__dirname, 'cm6_bundle.min.js'), 'utf8');

let passed = 0, failed = 0;
function check(label, cond) {
  if (cond) { passed++; console.log('  ✅ ' + label); }
  else { failed++; console.log('  ❌ ' + label); }
}

// --------------------------------------------------------------------
// The program, and the reference it is checked against
// --------------------------------------------------------------------
const DMEM_BASE = 0x10010000;
// Six pairs is what fits: the Wrapper's IROM is 2**9 bytes, so the whole
// program has to stay under 128 instructions. MCycle's own arithmetic is
// covered exhaustively by RV/test_MCycle_self_checking.v; what these have to
// reach is every decode path and the cases where the two engines could
// plausibly disagree.
const PAIRS = [
  [0xFFFFFFF9, 0x00000003],   // -7 /  3
  [0x00000007, 0xFFFFFFFD],   //  7 / -3
  [0xFFFFFFF9, 0xFFFFFFFD],   // -7 / -3
  [0x80000000, 0xFFFFFFFF],   // most negative / -1: the overflow case
  [0x12345678, 0x9ABCDEF0],   // a product that needs all 64 bits; mulhsu differs from mulhu here
  [0x00000005, 0x00000000],   // division by zero
];
const OPS = ['mul', 'mulh', 'mulhsu', 'mulhu', 'div', 'divu', 'rem', 'remu'];

const U32 = 0x100000000n;
const toS = v => (BigInt(v >>> 0) >= 0x80000000n ? BigInt(v >>> 0) - U32 : BigInt(v >>> 0));
const toU = v => BigInt(v >>> 0);
const wrap = b => Number(((b % U32) + U32) % U32) >>> 0;

function reference(op, a, b) {
  const sa = toS(a), sb = toS(b), ua = toU(a), ub = toU(b);
  switch (op) {
    case 'mul':    return wrap(sa * sb);
    case 'mulh':   return wrap((sa * sb) >> 32n);
    case 'mulhsu': return wrap((sa * ub) >> 32n);
    case 'mulhu':  return wrap((ua * ub) >> 32n);
    // RISC-V: x / 0 is all ones, x % 0 is x, and -2**31 / -1 is -2**31 rem 0.
    case 'div':    if (ub === 0n) return 0xFFFFFFFF;
                   if (sa === -(2n ** 31n) && sb === -1n) return 0x80000000;
                   return wrap(sa / sb);
    case 'divu':   return ub === 0n ? 0xFFFFFFFF : wrap(ua / ub);
    case 'rem':    if (ub === 0n) return wrap(sa);
                   if (sa === -(2n ** 31n) && sb === -1n) return 0;
                   return wrap(sa % sb);
    case 'remu':   return ub === 0n ? wrap(ua) : wrap(ua % ub);
  }
}

// x4 holds the store base; every result goes to its own word so the two
// engines can be compared word by word rather than only at the end.
function buildProgram() {
  const lines = ['# generated by test_m_extension.js', 'li x4, 0x10010000'];
  let off = 0;
  const slots = [];
  for (const [a, b] of PAIRS) {
    lines.push('li x1, 0x' + (a >>> 0).toString(16));
    lines.push('li x2, 0x' + (b >>> 0).toString(16));
    for (const op of OPS) {
      lines.push(op + ' x3, x1, x2');
      lines.push('sw x3, ' + off + '(x4)');
      slots.push({ op, a, b, addr: DMEM_BASE + off });
      off += 4;
    }
  }
  lines.push('halt: beq x0, x0, halt');
  return { src: lines.join('\n') + '\n', slots };
}

// --------------------------------------------------------------------
async function makeIcarus(testbench, sources) {
  const initIvlpp = (await import('file://' + path.join(ENGINE, 'ivlpp.js'))).default;
  const initIvl   = (await import('file://' + path.join(ENGINE, 'ivl.js'))).default;
  const initVvp   = (await import('file://' + path.join(ENGINE, 'vvp.js'))).default;

  const files = (sources ||
    DESIGN.map(n => ({ name: n, src: fs.readFileSync(path.join(RV, n), 'utf8') }))).slice();
  files.push({ name: 'cg3207_hdl_tb.v', src: testbench });

  const ppOut = [];
  const pp = await initIvlpp({ print: s => ppOut.push(s), printErr: () => {} });
  const args = ['-L'];
  for (const f of files) { pp.FS.writeFile('/' + f.name, f.src + '\n'); args.push('/' + f.name); }
  pp.callMain(args);

  const errs = [];
  const ivl = await initIvl({ print: () => {}, printErr: s => errs.push(s) });
  ivl.FS.writeFile('/ivl.conf',
    'basedir:/\nmodule:system.vpi\ngeneration:2005\ngeneration:no-specify\nout:/out.vvp\n' +
    'iwidth:32\nwidthcap:65536\nfunctor:cprop\nfunctor:nodangle\nflag:DLL=vvp.tgt\n');
  ivl.FS.writeFile('/src.v', ppOut.join('\n') + '\n');
  ivl.callMain(['-C/ivl.conf', '--', '/src.v']);

  let vvpBytes = null;
  try { vvpBytes = ivl.FS.readFile('/out.vvp'); } catch (e) {}
  const realErr = errs.filter(l => !/system\.vpi|dynamic linking not enabled/.test(l)).join('\n');
  if (!vvpBytes && realErr) console.log('    compile diagnostics:\n' + realErr);

  return {
    ok: !!vvpBytes,
    async run(plusargs, memFiles) {
      const out = [];
      const vvp = await initVvp({ print: s => out.push(s), printErr: s => out.push(s) });
      vvp.FS.writeFile('/sim.vvp', vvpBytes);
      for (const name of Object.keys(memFiles)) vvp.FS.writeFile('/' + name, memFiles[name]);
      vvp.callMain(['/sim.vvp'].concat(plusargs || []));
      return out.join('\n');
    }
  };
}

const dom = new JSDOM(html, {
  runScripts: 'dangerously', resources: 'usable',
  url: 'http://localhost:8080/riscv_simulator.html',
  beforeParse(window) {
    window.__CM6_DISABLE_CDN = true;
    window.addEventListener('DOMContentLoaded', () => {
      try { window.eval(CM6); } catch (e) { console.error('CM6 inject failed:', e.message); }
    });
    window.requestAnimationFrame = cb => setTimeout(cb, 16);
    window.cancelAnimationFrame = id => clearTimeout(id);
    window.matchMedia = () => ({ matches: false, addListener() {}, removeListener() {} });
    window.Range.prototype.getClientRects = () => [];
    window.Range.prototype.getBoundingClientRect = () => ({ top:0,bottom:0,left:0,right:0,width:0,height:0 });
    window.Element.prototype.getClientRects = () => [];
    window.Element.prototype.getBoundingClientRect = () => ({ top:0,bottom:0,left:0,right:0,width:0,height:0 });
    if (window.HTMLCanvasElement) {
      window.HTMLCanvasElement.prototype.getContext = () => ({
        createImageData: (w, h) => ({ data: new Uint8Array(w * h * 4) }),
        putImageData: () => {}, fillRect: () => {}, clearRect: () => {}
      });
    }
    installExamplesFetch(window);
  }
});

const win = dom.window;
const doc = win.document;

setTimeout(async () => {
  try {
    console.log('===========================================================');
    console.log('✖️  RV32M: MCycle.v vs the JS engine vs a BigInt reference');
    console.log('===========================================================');

    const { src, slots } = buildProgram();

    // --- 1. The assembler ---------------------------------------------
    console.log('\n[1] The program assembles');
    win.editor.value = src;
    const mc = win.assembleOnly();
    check('Assembled (' + (mc ? mc.length : 0) + ' instructions)', Array.isArray(mc) && mc.length > 0);
    const word = w => w.bytes && w.bytes.length === 4
      ? ((w.bytes[0] | (w.bytes[1] << 8) | (w.bytes[2] << 16) | (w.bytes[3] << 24)) >>> 0) : 0;
    const mWords = mc.filter(w => (word(w) & 0x7f) === 0x33 && (word(w) >>> 25) === 0x01);
    check('Every M instruction encoded with funct7 = 0000001 (' + mWords.length + ')',
      mWords.length === PAIRS.length * OPS.length);
    // Silent truncation of the IROM image is what a too-long program looks
    // like from the hardware side, so fail on the length rather than on the
    // puzzling half-finished run it produces.
    check('Program fits the Wrapper\'s 128-word IROM (' + mc.length + ')', mc.length <= 128);

    // --- 2. The JS engine ---------------------------------------------
    console.log('\n[2] The JS functional model');
    win.resetAll();
    win.assembleOnly();
    // Step to the halt loop rather than for a fixed count: every step drives a
    // full panel refresh in jsdom, so the spare ones are not free.
    let steps = 0;
    for (; steps < 400; steps++) {
      const before = win.getPc();
      win.stepOnce();
      if (win.getPc() === before) break;
    }
    console.log('     JS reached the halt loop after ' + steps + ' steps, at PC 0x' +
      (win.getPc() >>> 0).toString(16));
    check('Reached the halt loop rather than running off the end', steps < 399);
    const jsMem = slots.map(s => win.readMem(s.addr, 4) >>> 0);
    let jsBad = 0;
    slots.forEach((s, i) => {
      const want = reference(s.op, s.a, s.b);
      if (jsMem[i] !== want) {
        jsBad++;
        if (jsBad < 6) console.log('     JS  ' + s.op + ' ' + hex(s.a) + ',' + hex(s.b) +
          ' -> ' + hex(jsMem[i]) + ', reference ' + hex(want));
      }
    });
    check('All ' + slots.length + ' results match the BigInt reference', jsBad === 0);

    // --- 3. The hardware ----------------------------------------------
    console.log('\n[3] RV/*.v through Icarus');
    if (!fs.existsSync(path.join(ENGINE, 'ivl.js'))) {
      check('Engine present at ' + ENGINE + ' (set HDL_ENGINE_DIR to override)', false);
    } else {
      win.hdlSetSources(DESIGN.map(n => ({ name: n, src: fs.readFileSync(path.join(RV, n), 'utf8') })));
      const tb = win.hdlBuildTestbench({ regBankPath: win.hdlDiscoverRegBank() });
      const wrapperSrc = fs.readFileSync(path.join(RV, 'Wrapper.v'), 'utf8');
      const mem = win.hdlMemFiles(wrapperSrc);
      const icarus = await makeIcarus(tb);
      check('Design and testbench compile', icarus.ok);

      if (icarus.ok) {
        // Every signed multiply is 64 cycles and every divide 32, plus the
        // li/sw around them, so the run has to be long enough to finish.
        const out = await icarus.run(['+CYCLES=6000'], {
          'AA_IROM.mem': mem.files['AA_IROM.mem'],
          'AA_DMEM.mem': mem.files['AA_DMEM.mem'],
          'stim.mem': '', 'uart_rx.mem': ''
        });
        const trace = win.hdlParseTrace(out);
        check('Trace captured (' + trace.steps.length + ' instructions)', trace.steps.length > 100);

        // Last write wins, as in memory.
        const hw = new Map();
        for (const st of trace.steps) for (const w of st.memw) hw.set(w[0] >>> 0, w[2] >>> 0);
        check('Every result word was stored (' + hw.size + ')', hw.size >= slots.length);

        let hwBad = 0, shown = 0;
        slots.forEach((s, i) => {
          const got = hw.get(s.addr >>> 0);
          const want = reference(s.op, s.a, s.b);
          if (got !== want) {
            hwBad++;
            if (shown++ < 8) console.log('     HDL ' + s.op + ' ' + hex(s.a) + ',' + hex(s.b) +
              ' -> ' + (got === undefined ? 'not stored' : hex(got)) + ', reference ' + hex(want));
          }
        });
        check('All ' + slots.length + ' hardware results match the reference', hwBad === 0);
        check('The hardware and the JS engine agree word for word',
          slots.every((s, i) => hw.get(s.addr >>> 0) === jsMem[i]));

        // A multi-cycle instruction must retire once, not once per cycle: the
        // PC has to be frozen while Busy and the write-back has to be single.
        console.log('\n[4] The stall');
        const pcs = trace.steps.map(s => s.pc);
        check('No PC is executed twice in a row', pcs.every((p, i) => i === 0 || p !== pcs[i - 1]));
        // The trace finds register writes by shadow-comparing the array, so a
        // write of the value already there is invisible. Count the results
        // that actually change x3 rather than all of them.
        let prevX3 = 0, changing = 0;
        for (const s of slots) {
          const v = reference(s.op, s.a, s.b);
          if (v !== prevX3) changing++;
          prevX3 = v;
        }
        const x3Writes = trace.steps.reduce((n, s) =>
          n + s.regw.filter(w => w[0] === 3).length, 0);
        check('x3 changes exactly as often as the results do (' + x3Writes +
          ' of ' + slots.length + ')', x3Writes === changing);
        check('No instruction writes x3 more than once',
          trace.steps.every(s => s.regw.filter(w => w[0] === 3).length <= 1));
        // Each M instruction costs many cycles; a non-stalling core would
        // retire one per cycle like everything else.
        const mSteps = trace.steps.filter(s =>
          (s.instr & 0x7f) === 0x33 && (s.instr >>> 25) === 0x01);
        const gaps = mSteps.map(s => {
          const idx = trace.steps.indexOf(s);
          return idx + 1 < trace.steps.length ? trace.steps[idx + 1].cyc - s.cyc : null;
        }).filter(g => g !== null);
        check('Every M instruction takes more than one cycle (min ' +
          Math.min.apply(null, gaps) + ', max ' + Math.max.apply(null, gaps) + ')',
          gaps.every(g => g > 1));
        check('Signed multiply is the longest at 2*32 + 1 cycles (max ' +
          Math.max.apply(null, gaps) + ')', Math.max.apply(null, gaps) === 65);

        // --- 5. The shipped, pre-synthesised copy ---------------------
        // examples/hdl/RV_reference.v is generated from these same sources, so
        // it goes stale silently if RV/ changes and nobody reruns the build
        // script. Running the same program through it is what notices.
        console.log('\n[5] examples/hdl/RV_reference.v, the pre-synthesised core');
        const refDir = path.join(ROOT, 'examples', 'hdl');
        const refFiles = ['Wrapper.v', 'RV_reference.v']
          .map(n => ({ name: n, src: fs.readFileSync(path.join(refDir, n), 'utf8') }));
        check('The Wrapper copy is identical to RV/Wrapper.v',
          refFiles[0].src === fs.readFileSync(path.join(RV, 'Wrapper.v'), 'utf8'));
        check('Internal names are gone (no ALU1 / Src_A / shifted_op1)',
          !/\b(ALU1|Src_A|shifted_op1|temp_sum|MCycleOp)\b/.test(refFiles[1].src));

        win.hdlSetSources(refFiles);
        const refPath = win.hdlDiscoverRegBank();
        check('The register file survived the flattening: ' + refPath,
          refPath === 'dut.RV1.RegFile1.RegBank');

        const refIcarus = await makeIcarus(
          win.hdlBuildTestbench({ regBankPath: refPath }), refFiles);
        check('The reference core compiles against the fixed Wrapper', refIcarus.ok);
        if (refIcarus.ok) {
          const refOut = await refIcarus.run(['+CYCLES=6000'], {
            'AA_IROM.mem': mem.files['AA_IROM.mem'],
            'AA_DMEM.mem': mem.files['AA_DMEM.mem'],
            'stim.mem': '', 'uart_rx.mem': ''
          });
          const refTrace = win.hdlParseTrace(refOut);
          const refHw = new Map();
          for (const st of refTrace.steps) for (const w of st.memw) refHw.set(w[0] >>> 0, w[2] >>> 0);
          check('It runs the same RV32M program to the same ' + slots.length + ' results',
            slots.every(s => refHw.get(s.addr >>> 0) === reference(s.op, s.a, s.b)));
          check('It still reports register writes, so the Registers panel works',
            refTrace.steps.reduce((n, s) => n + s.regw.length, 0) > 10);
        }
      }
    }

    console.log('\n===========================================================');
    if (failed === 0) console.log('🎉 ALL ' + passed + ' RV32M TESTS PASSED!');
    else console.log('💥 ' + failed + ' RV32M TEST(S) FAILED (' + passed + ' passed)');
    process.exit(failed === 0 ? 0 : 1);
  } catch (e) {
    console.error('FATAL', e);
    process.exit(1);
  }
}, 4000);

function hex(v) { return '0x' + (v >>> 0).toString(16).padStart(8, '0'); }
